name: HyperClaims
main: dev._2lstudios.hyperclaims.HyperClaims
version: 0.0.1
author: 2LStudios
depend: [WorldSentinel, Vault, ProtocolLib]
commands:
  hyperclaims:
    aliases:
      - claim
    description: HyperClaims main command